export const theme = {
  colors: {
    primary: "#F5A623",
    primaryHover: "#E09500",
    background: "#ffffff",
    backgroundDark: "#1a1a1a",
    backgroundCard: "#ffffff",
    backgroundDarkCard: "#1e1e1e",
    backgroundInput: "#ffffff",
    backgroundDarkInput: "#333333",
    border: "#dddddd",
    borderDark: "#444444",
    text: "#1a1a1a",
    textLight: "#555555",
    textMuted: "#aaaaaa",
    textWhite: "#ffffff",
    textDark: "#d0d0d0",
    error: "#ef4444",
    errorBackground: "#2d1515",
    success: "#22c55e",
  },
  borderRadius: {
    sm: "6px",
    md: "8px",
    lg: "12px",
  },
  spacing: {
    xs: "4px",
    sm: "8px",
    md: "16px",
    lg: "24px",
    xl: "40px",
    xxl: "60px",
  },
  fontSize: {
    xs: "0.75rem",
    sm: "0.85rem",
    md: "0.95rem",
    lg: "1rem",
    xl: "1.4rem",
    xxl: "2rem",
  },
  fontWeight: {
    normal: 400,
    semibold: 600,
    bold: 700,
  },
} as const;
