export const ICON_PT_MAP: Record<string, string> = {
  carrinho: "ShoppingCart",
  compras: "ShoppingCart",
  sacola: "ShoppingBag",
  restaurante: "UtensilsCrossed",
  comida: "UtensilsCrossed",
  alimentacao: "UtensilsCrossed",
  cafe: "Coffee",
  cafezinho: "Coffee",
  pizza: "Pizza",
  maca: "Apple",
  fruta: "Apple",
  vinho: "Wine",
  bebida: "Wine",
  alcool: "Wine",
  sanduiche: "Sandwich",
  lanche: "Sandwich",
  casa: "Home",
  moradia: "Home",
  predio: "Building",
  edificio: "Building2",
  lampada: "Lightbulb",
  luz: "Lightbulb",
  ferramenta: "Wrench",
  chave: "Wrench",
  manutencao: "Wrench",
  martelo: "Hammer",
  construcao: "Hammer",
  cama: "Bed",
  quarto: "Bed",
  sofa: "Sofa",
  sala: "Sofa",
  poltrona: "Armchair",
  carro: "Car",
  automovel: "Car",
  veiculo: "Car",
  onibus: "Bus",
  transporte: "Bus",
  trem: "Train",
  metro: "Train",
  aviao: "Plane",
  voo: "Plane",
  viagem: "Plane",
  bicicleta: "Bike",
  bike: "Bike",
  combustivel: "Fuel",
  gasolina: "Fuel",
  estacionamento: "ParkingCircle",
  coracao: "Heart",
  saude: "Heart",
  atividade: "Activity",
  remedio: "Pill",
  medicamento: "Pill",
  farmacia: "Pill",
  medico: "Stethoscope",
  hospital: "Stethoscope",
  curativo: "Bandage",
  olho: "Eye",
  visao: "Eye",
  dolar: "DollarSign",
  dinheiro: "DollarSign",
  cartao: "CreditCard",
  credito: "CreditCard",
  carteira: "Wallet",
  tendencia: "TrendingUp",
  crescimento: "TrendingUp",
  grafico: "BarChart",
  porquinho: "PiggyBank",
  poupanca: "PiggyBank",
  recibo: "Receipt",
  nota: "Receipt",
  livro: "BookOpen",
  leitura: "BookOpen",
  formatura: "GraduationCap",
  educacao: "GraduationCap",
  faculdade: "GraduationCap",
  lapis: "Pencil",
  caneta: "Pencil",
  escola: "School",
  colegio: "School",
  mochila: "Backpack",
  controle: "Gamepad2",
  jogo: "Gamepad2",
  fone: "Headphones",
  audio: "Headphones",
  musica: "Music",
  camera: "Camera",
  foto: "Camera",
  televisao: "Tv",
  televisor: "Tv",
  estrela: "Star",
  favorito: "Star",
  celular: "Smartphone",
  telefone: "Smartphone",
  monitor: "Monitor",
  tela: "Monitor",
  notebook: "Laptop",
  computador: "Laptop",
  internet: "Wifi",
  pasta: "Briefcase",
  trabalho: "Briefcase",
  emprego: "Briefcase",
  usuarios: "Users",
  pessoas: "Users",
  grupo: "Users",
  mundo: "Globe",
  globo: "Globe",
  pacote: "Package",
  entrega: "Package",
  presente: "Gift",
  presentes: "Gift",
  tesoura: "Scissors",
  corte: "Scissors",
  camisa: "Shirt",
  roupa: "Shirt",
  vestuario: "Shirt",
  etiqueta: "Tag",
  preco: "Tag",
  sol: "Sun",
  raio: "Zap",
  energia: "Zap",
  eletricidade: "Zap",
  gato: "Cat",
  bichano: "Cat",
  cachorro: "Dog",
  animal: "Dog",
  sino: "Bell",
  notificacao: "Bell",
  paleta: "Palette",
  arte: "Palette",
  cedula: "Banknote",
  dinheirinho: "Banknote",
  mapa: "Map",
  localizacao: "Map",
  bussola: "Compass",
  direcao: "Compass",
  guarda_chuva: "Umbrella",
  chuva: "Umbrella",
  halter: "Dumbbell",
  academia: "Dumbbell",
  ginastica: "Dumbbell",
  pessoa: "PersonStanding",
};

export const ICON_LIST = [
  "ShoppingCart",
  "ShoppingBag",
  "UtensilsCrossed",
  "Coffee",
  "Pizza",
  "Apple",
  "Wine",
  "Sandwich",
  "Home",
  "Building",
  "Building2",
  "Lightbulb",
  "Wrench",
  "Hammer",
  "Bed",
  "Sofa",
  "Armchair",
  "Car",
  "Bus",
  "Train",
  "Plane",
  "Bike",
  "Fuel",
  "ParkingCircle",
  "Heart",
  "Activity",
  "Pill",
  "Stethoscope",
  "Bandage",
  "Eye",
  "DollarSign",
  "CreditCard",
  "Wallet",
  "TrendingUp",
  "BarChart",
  "PiggyBank",
  "Receipt",
  "BookOpen",
  "GraduationCap",
  "Pencil",
  "School",
  "Backpack",
  "Gamepad2",
  "Headphones",
  "Camera",
  "Tv",
  "Star",
  "Smartphone",
  "Monitor",
  "Laptop",
  "Wifi",
  "Briefcase",
  "Users",
  "BarChart2",
  "Globe",
  "Package",
  "Gift",
  "Scissors",
  "Shirt",
  "Tag",
  "Sun",
  "Zap",
  "Cat",
  "Dog",
  "Bell",
  "Music",
  "Palette",
  "Banknote",
  "Map",
  "Compass",
  "Umbrella",
  "Dumbbell",
  "PersonStanding",
];
